import { useEffect, useMemo, useState } from 'react'
import { Download, FileText, FolderKanban, RefreshCw, Search, Ticket, Trash2 } from 'lucide-react'
import { supabase } from '../lib/supabase'

const nameOf=p=>String(p||'').split('/').pop()||'File'
const dateOf=v=>v?new Date(v).toLocaleString([], {dateStyle:'medium',timeStyle:'short'}):'—'
export default function AdminFilesPage(){const[files,setFiles]=useState([]),[projects,setProjects]=useState([]),[tickets,setTickets]=useState([]),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState('')
 const load=async()=>{setLoading(true);setError('');const[{data:f,error:fe},{data:p,error:pe},{data:t,error:te}]=await Promise.all([supabase.from('files').select('id,owner_id,bucket,storage_path,mime_type,size,visibility,project_id,ticket_id,created_at,owner:profiles!files_owner_id_fkey(full_name)').order('created_at',{ascending:false}),supabase.from('projects').select('id,title').order('updated_at',{ascending:false}),supabase.from('tickets').select('id,subject').order('updated_at',{ascending:false})]);if(fe)setError(fe.message);else setFiles(f||[]);if(pe)setError(x=>x||pe.message);else setProjects(p||[]);if(te)setError(x=>x||te.message);else setTickets(t||[]);setLoading(false)}
 useEffect(()=>{load()},[])
 const projectMap=useMemo(()=>Object.fromEntries(projects.map(x=>[x.id,x.title])),[projects]);const ticketMap=useMemo(()=>Object.fromEntries(tickets.map(x=>[x.id,x.subject])),[tickets])
 const visible=useMemo(()=>{const q=search.trim().toLowerCase();return files.filter(f=>{const kind=f.project_id?'project':f.ticket_id?'ticket':'unassociated';return (filter==='all'||kind===filter)&&(!q||`${nameOf(f.storage_path)} ${f.mime_type||''} ${projectMap[f.project_id]||''} ${ticketMap[f.ticket_id]||''} ${f.owner?.full_name||''}`.toLowerCase().includes(q))})},[files,search,filter,projectMap,ticketMap])
 async function download(f){setBusy(`d-${f.id}`);setError('');const{data,error:e}=await supabase.storage.from(f.bucket).download(f.storage_path);if(e)setError(e.message);else{const u=URL.createObjectURL(data);const a=document.createElement('a');a.href=u;a.download=nameOf(f.storage_path);document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(u)}setBusy('')}
 async function remove(f){if(!window.confirm(`Delete ${nameOf(f.storage_path)}?`))return;setBusy(`x-${f.id}`);setError('');const{error:se}=await supabase.storage.from(f.bucket).remove([f.storage_path]);if(se){setError(se.message);setBusy('');return}const{error:de}=await supabase.from('files').delete().eq('id',f.id);if(de)setError(de.message);else{setFiles(xs=>xs.filter(x=>x.id!==f.id));setMessage('File deleted.')}setBusy('')}
 return <div><div className="page-intro"><div><p className="eyebrow">DOCUMENT CONTROL</p><h1>Files</h1><p className="muted">Private project and ticket documents with database relationships preserved.</p></div><button className="icon-btn" onClick={load} title="Refresh"><RefreshCw size={16}/></button></div>{message&&<div className="alert success">{message}</div>}{error&&<div className="alert danger">{error}</div>}<section className="panel"><div className="panel-head"><div><p className="eyebrow">LIVE STORAGE INDEX</p><h3>{loading?'Loading…':`${visible.length} file${visible.length===1?'':'s'}`}</h3></div><div className="search-box"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search file, project, ticket…"/></div></div><div className="inquiry-tabs">{[['all','All'],['project','Projects'],['ticket','Tickets'],['unassociated','Unassociated']].map(([v,l])=><button key={v} className={filter===v?'active':''} onClick={()=>setFilter(v)}>{l}</button>)}</div>{loading?<div className="empty">Loading files…</div>:visible.length===0?<div className="empty"><FileText size={25}/><p>No files match the current filters.</p></div>:<div className="table-wrap"><table><thead><tr><th>File</th><th>Relationship</th><th>Owner</th><th>Type</th><th>Size</th><th>Added</th><th></th></tr></thead><tbody>{visible.map(f=><tr key={f.id}><td><strong>{nameOf(f.storage_path)}</strong><small className="table-sub">{f.bucket}</small></td><td>{f.project_id?<span><FolderKanban size={14}/> {projectMap[f.project_id]||'Project'}</span>:f.ticket_id?<span><Ticket size={14}/> {ticketMap[f.ticket_id]||'Ticket'}</span>:'Unassociated'}</td><td>{f.owner?.full_name||'—'}</td><td>{f.mime_type||'—'}</td><td>{f.size?`${Math.max(1,Math.round(f.size/1024))} KB`:'—'}</td><td>{dateOf(f.created_at)}</td><td><button className="text-link" onClick={()=>download(f)} disabled={busy===`d-${f.id}`}><Download size={14}/> {busy===`d-${f.id}`?'…':'Download'}</button><button className="text-link" onClick={()=>remove(f)} disabled={busy===`x-${f.id}`}><Trash2 size={14}/></button></td></tr>)}</tbody></table></div>}</section></div>
}
