import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { ArrowLeft, CheckCircle2, Send, UserCheck } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { useAuth } from '../auth/AuthProvider'

const statuses=['open','in_progress','waiting','resolved','closed']; const priorities=['low','normal','high','urgent']
export default function AdminTicketDetail(){const{ticketId}=useParams();const{profile}=useAuth();const[ticket,setTicket]=useState(null);const[messages,setMessages]=useState([]);const[staff,setStaff]=useState([]);const[reply,setReply]=useState('');const[error,setError]=useState('');const[saving,setSaving]=useState(false);const[message,setMessage]=useState('')
 const load=async()=>{const[{data:t,error:te},{data:m,error:me},{data:s,error:se}]=await Promise.all([supabase.from('tickets').select('*,client:profiles!tickets_client_id_fkey(id,full_name,email),assignee:profiles!tickets_assignee_id_fkey(id,full_name)').eq('id',ticketId).single(),supabase.from('ticket_messages').select('id,author_id,body,created_at,author:profiles!ticket_messages_author_id_fkey(full_name)').eq('ticket_id',ticketId).order('created_at'),supabase.from('profiles').select('id,full_name,role').in('role',['staff','admin']).order('full_name')]);if(te)setError(te.message);else setTicket(t);if(me)setError(x=>x||me.message);else setMessages(m||[]);if(se)setError(x=>x||se.message);else setStaff(s||[])}
 useEffect(()=>{load()},[ticketId])
 const update=async(patch,success='Ticket updated.')=>{setSaving(true);setError('');const{data,error:e}=await supabase.from('tickets').update(patch).eq('id',ticketId).select('*,client:profiles!tickets_client_id_fkey(id,full_name,email),assignee:profiles!tickets_assignee_id_fkey(id,full_name)').single();if(e)setError(e.message);else{setTicket(data);setMessage(success);await load()}setSaving(false)}
 const send=async e=>{e.preventDefault();if(!reply.trim()||!profile)return;setSaving(true);setError('');const{error:e2}=await supabase.from('ticket_messages').insert({ticket_id:ticketId,author_id:profile.id,body:reply.trim()});if(e2)setError(e2.message);else{setReply('');setMessage('Reply sent.');await load()}setSaving(false)}
 if(!ticket)return <div className="empty">{error||'Loading ticket…'}</div>
 return <div><Link to="/tickets" className="text-link"><ArrowLeft size={15}/> Back to tickets</Link><div className="page-intro"><div><p className="eyebrow">SUPPORT TICKET</p><h1>{ticket.subject}</h1><p className="muted">{ticket.client?.full_name||ticket.client?.email||'Client'} · {new Date(ticket.created_at).toLocaleString()}</p></div></div>{error&&<div className="alert danger">{error}</div>}{message&&<div className="alert success"><CheckCircle2 size={15}/> {message}</div>}<div className="section-grid"><section className="panel"><div className="panel-head"><h3>Conversation</h3></div><div className="activity-list">{messages.length?messages.map(m=><article className="note-item" key={m.id}><div><strong>{m.author_id===profile?.id?'You':m.author?.full_name||'Team member'}</strong><small>{new Date(m.created_at).toLocaleString()}</small></div><p>{m.body}</p></article>):<div className="empty">No messages yet.</div>}</div><form onSubmit={send} className="note-form"><textarea value={reply} onChange={e=>setReply(e.target.value)} placeholder="Reply to the client…" required/><button className="primary" disabled={saving}>{saving?'Sending…':<><Send size={15}/> Send reply</>}</button></form></section><aside className="panel"><div className="panel-head"><h3>Ticket workflow</h3><UserCheck size={17}/></div><label>Status<select value={ticket.status} onChange={e=>update({status:e.target.value})} disabled={saving}>{statuses.map(x=><option key={x} value={x}>{x.replace('_',' ')}</option>)}</select></label><label>Priority<select value={ticket.priority} onChange={e=>update({priority:e.target.value})} disabled={saving}>{priorities.map(x=><option key={x} value={x}>{x}</option>)}</select></label><label>Assign to<select value={ticket.assignee_id||''} onChange={e=>update({assignee_id:e.target.value||null},e.target.value?'Ticket assigned.':'Ticket unassigned.')} disabled={saving}><option value="">Unassigned</option>{staff.map(x=><option key={x.id} value={x.id}>{x.full_name||x.role}</option>)}</select></label><p className="muted">Client<br/><strong>{ticket.client?.full_name||'Unnamed'}</strong><br/>{ticket.client?.email||'—'}</p><div className="security-note"><UserCheck size={15}/> Assignment changes are persisted on the ticket and trigger the existing operational event engine.</div></aside></div></div>
}
