import { useEffect, useMemo, useState } from 'react'
import { ArrowUpRight, Plus, RefreshCw, Search, UserRound, X } from 'lucide-react'
import { NavLink } from 'react-router-dom'
import { supabase } from '../lib/supabase'

const initial={full_name:'',phone:'',email:'',address:'',customer_status:'active',notes:'',profile_id:''}
export default function CustomersPage(){
 const[rows,setRows]=useState([]),[profiles,setProfiles]=useState([]),[search,setSearch]=useState(''),[modal,setModal]=useState(false),[selected,setSelected]=useState(null),[form,setForm]=useState(initial),[error,setError]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(true)
 const load=async()=>{setLoading(true);setError('');const[a,b]=await Promise.all([supabase.from('customers').select('id,profile_id,full_name,phone,email,address,customer_status,notes,created_at,updated_at').order('updated_at',{ascending:false}),supabase.from('profiles').select('id,full_name,phone,company,role').eq('role','client').order('full_name')]);if(a.error)setError(a.error.message);else setRows(a.data||[]);if(b.error)setError(x=>x||b.error.message);else{const ids=(b.data||[]).map(p=>p.id);if(ids.length){const{data:users,error:e}=await supabase.rpc('get_client_identity_emails',{p_user_ids:ids});if(!e){const emailById=Object.fromEntries((users||[]).map(u=>[u.user_id,u.email]));setProfiles((b.data||[]).map(p=>({...p,email:emailById[p.id]||''})))}else setProfiles((b.data||[]).map(p=>({...p,email:''})))}else setProfiles([])}setLoading(false)}
 useEffect(()=>{load()},[])
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return rows.filter(r=>!q||`${r.full_name} ${r.phone} ${r.email} ${r.address} ${r.customer_status}`.toLowerCase().includes(q))},[rows,search])
 const stats=useMemo(()=>({total:rows.length,active:rows.filter(x=>x.customer_status==='active').length,accounts:rows.filter(x=>x.profile_id).length,walkins:rows.filter(x=>!x.profile_id).length}),[rows])
 const openCreate=()=>{setSelected(null);setForm(initial);setError('');setMessage('');setModal(true)}
 const openEdit=r=>{setSelected(r);setForm({...initial,...r,profile_id:r.profile_id||''});setError('');setMessage('');setModal(true)}
 const selectProfile=id=>{const p=profiles.find(x=>x.id===id);setForm(x=>({...x,profile_id:id,full_name:x.full_name||p?.full_name||'',phone:x.phone||p?.phone||'',email:x.email||p?.email||''}))}
 const save=async e=>{e.preventDefault();if(!form.full_name.trim())return setError('Customer name is required.');if(!form.phone.trim())return setError('Phone is required for new customer intake.');setLoading(true);const payload={full_name:form.full_name.trim(),phone:form.phone.trim(),email:form.email.trim()||null,address:form.address.trim()||null,customer_status:form.customer_status,notes:form.notes.trim()||null,profile_id:form.profile_id||null};const{error:e2}=selected?await supabase.from('customers').update(payload).eq('id',selected.id):await supabase.from('customers').insert(payload);if(e2)setError(e2.message);else{setMessage(selected?'Customer updated.':'Customer created.');setModal(false);await load()}setLoading(false)}
 return <div className="workspace workspace-customers">
  <div className="page-intro"><div><p className="eyebrow">CUSTOMER RELATIONSHIPS</p><h1>Customers</h1><p className="muted">One reusable customer record across walk-ins, accounts, repairs and future services.</p></div><div className="team-actions"><button className="icon-btn" onClick={load} title="Refresh"><RefreshCw size={16}/></button><button className="primary" onClick={openCreate}><Plus size={16}/> New customer</button></div></div>
  {message&&<div className="alert success">{message}</div>}{error&&<div className="alert danger">{error}</div>}
  <section className="workspace-grid workspace-grid-four">
   <div className="metric"><span>Total customers</span><strong>{loading?'—':stats.total}</strong><small>Reusable customer records</small></div>
   <div className="metric"><span>Active</span><strong>{loading?'—':stats.active}</strong><small>Currently active relationships</small></div>
   <div className="metric"><span>Accounts</span><strong>{loading?'—':stats.accounts}</strong><small>Linked authenticated clients</small></div>
   <div className="metric"><span>Walk-ins</span><strong>{loading?'—':stats.walkins}</strong><small>No portal account required</small></div>
  </section>
  <section className="panel"><div className="panel-head"><div><p className="eyebrow">RELATIONSHIP DIRECTORY</p><h3>{loading?'Loading…':`${filtered.length} customer${filtered.length===1?'':'s'}`}</h3><p className="muted">Search first; open a record only when you need to change customer data.</p></div><div className="search-box"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name, phone or email"/></div></div>{filtered.length?<div className="table-wrap"><table><thead><tr><th>Customer</th><th>Contact</th><th>Relationship</th><th>Status</th><th></th></tr></thead><tbody>{filtered.map(r=><tr key={r.id} className="clickable-row" onClick={()=>openEdit(r)}><td><strong>{r.full_name}</strong>{r.address&&<small className="table-sub">{r.address}</small>}</td><td>{r.phone||'—'}<small className="table-sub">{r.email||'No email'}</small></td><td><span className="chip">{r.profile_id?'ACCOUNT':'WALK-IN'}</span></td><td>{r.customer_status}</td><td><ArrowUpRight size={15}/></td></tr>)}</tbody></table></div>:<div className="empty-state-rich"><div className="empty-icon"><UserRound size={20}/></div><div><strong>No customer records yet</strong><p>Create a customer during repair intake or add one directly here.</p></div><button className="secondary" onClick={openCreate}><Plus size={14}/> Add customer</button></div>}</section>
  <div className="workspace-footer-links"><NavLink to="/repairs" className="secondary">Open repair desk <ArrowUpRight size={14}/></NavLink><NavLink to="/projects" className="secondary">Open projects <ArrowUpRight size={14}/></NavLink></div>
  {modal&&<div className="modal-backdrop"><form className="modal-card" onSubmit={save}><div className="panel-head"><div><p className="eyebrow">{selected?'EDIT CUSTOMER':'NEW CUSTOMER'}</p><h3>{selected?'Customer record':'Customer intake'}</h3></div><button type="button" className="icon-btn" onClick={()=>setModal(false)}><X size={18}/></button></div><label>Registered account (optional)<select value={form.profile_id} onChange={e=>selectProfile(e.target.value)}><option value="">Walk-in / non-account customer</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.full_name||p.email||p.id}</option>)}</select></label><label>Full name<input value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})} required/></label><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} required/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Address<input value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><label>Status<select value={form.customer_status} onChange={e=>setForm({...form,customer_status:e.target.value})}><option>active</option><option>inactive</option><option>archived</option></select></label><label>Notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="primary full" disabled={loading}>{loading?'Saving…':'Save customer'}</button></form></div>}
 </div>
}
