import { useEffect, useMemo, useState } from 'react'
import { Plus, RefreshCw, Search, X } from 'lucide-react'
import { supabase } from '../lib/supabase'

const initial={full_name:'',phone:'',email:'',address:'',customer_status:'active',notes:'',profile_id:''}
export default function CustomersPage(){const[rows,setRows]=useState([]),[profiles,setProfiles]=useState([]),[search,setSearch]=useState(''),[modal,setModal]=useState(false),[selected,setSelected]=useState(null),[form,setForm]=useState(initial),[error,setError]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(true)
 const load=async()=>{setLoading(true);setError('');const[a,b]=await Promise.all([supabase.from('customers').select('id,profile_id,full_name,phone,email,address,customer_status,notes,created_at,updated_at').order('updated_at',{ascending:false}),supabase.from('profiles').select('id,full_name,phone,company,role').eq('role','client').order('full_name')]);if(a.error)setError(a.error.message);else setRows(a.data||[]);if(b.error)setError(x=>x||b.error.message);else{const ids=(b.data||[]).map(p=>p.id);if(ids.length){const{data:users,error:e}=await supabase.rpc('get_client_identity_emails',{p_user_ids:ids});if(!e){const emailById=Object.fromEntries((users||[]).map(u=>[u.user_id,u.email]));setProfiles((b.data||[]).map(p=>({...p,email:emailById[p.id]||''})))}else setProfiles((b.data||[]).map(p=>({...p,email:''})))}else setProfiles([])}setLoading(false)};useEffect(()=>{load()},[])
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return rows.filter(r=>!q||JSON.stringify(r).toLowerCase().includes(q))},[rows,search])
 const openCreate=()=>{setSelected(null);setForm(initial);setError('');setMessage('');setModal(true)}
 const openEdit=r=>{setSelected(r);setForm({...initial,...r,profile_id:r.profile_id||''});setError('');setMessage('');setModal(true)}
 const selectProfile=id=>{const p=profiles.find(x=>x.id===id);setForm(x=>({...x,profile_id:id,full_name:x.full_name||p?.full_name||'',phone:x.phone||p?.phone||'',email:x.email||p?.email||''}))}
 const save=async e=>{e.preventDefault();if(!form.full_name.trim())return setError('Customer name is required.');if(!form.phone.trim())return setError('Phone is required for new customer intake.');setLoading(true);const payload={full_name:form.full_name.trim(),phone:form.phone.trim(),email:form.email.trim()||null,address:form.address.trim()||null,customer_status:form.customer_status,notes:form.notes.trim()||null,profile_id:form.profile_id||null};const{error:e2}=selected?await supabase.from('customers').update(payload).eq('id',selected.id):await supabase.from('customers').insert(payload);if(e2)setError(e2.message);else{setMessage(selected?'Customer updated.':'Customer created.');setModal(false);await load()}setLoading(false)}
 return <div><div className="page-intro"><div><p className="eyebrow">CUSTOMER MANAGEMENT</p><h1>Customers</h1><p className="muted">One customer record for both walk-in clients and registered CypherTech accounts.</p></div><div className="team-actions"><button className="icon-btn" onClick={load}><RefreshCw size={16}/></button><button className="primary" onClick={openCreate}><Plus size={16}/> New customer</button></div></div>{message&&<div className="alert success">{message}</div>}{error&&<div className="alert danger">{error}</div>}<section className="panel"><div className="panel-head"><div><p className="eyebrow">LIVE DATABASE</p><h3>{loading?'Loading…':`${filtered.length} customer${filtered.length===1?'':'s'}`}</h3></div><div className="search-box"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search customers"/></div></div>{filtered.length?<div className="table-wrap"><table><thead><tr><th>Name</th><th>Phone</th><th>Email</th><th>Type</th><th>Status</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id} className="clickable-row" onClick={()=>openEdit(r)}><td><strong>{r.full_name}</strong>{r.address&&<small className="table-sub">{r.address}</small>}</td><td>{r.phone||'—'}</td><td>{r.email||'—'}</td><td><span className="chip">{r.profile_id?'ACCOUNT':'WALK-IN'}</span></td><td>{r.customer_status}</td></tr>)}</tbody></table></div>:<div className="empty">No customer records yet.</div>}</section>
 {modal&&<div className="modal-backdrop"><form className="modal-card" onSubmit={save}><div className="panel-head"><div><p className="eyebrow">{selected?'EDIT CUSTOMER':'NEW CUSTOMER'}</p><h3>{selected?'Customer record':'Customer intake'}</h3></div><button type="button" className="icon-btn" onClick={()=>setModal(false)}><X size={18}/></button></div><label>Registered account (optional)<select value={form.profile_id} onChange={e=>selectProfile(e.target.value)}><option value="">Walk-in / non-account customer</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.full_name||p.email||p.id}</option>)}</select></label><label>Full name<input value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})} required/></label><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} required/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Address<input value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><label>Status<select value={form.customer_status} onChange={e=>setForm({...form,customer_status:e.target.value})}><option>active</option><option>inactive</option><option>archived</option></select></label><label>Notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="primary full" disabled={loading}>{loading?'Saving…':'Save customer'}</button></form></div>}</div>}
