import { useEffect, useState } from 'react'
import { Plus, RefreshCw, X } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { getFinanceSummary, money, dateTime, dateOnly } from '../lib/data'
import { useAuth } from '../auth/AuthProvider'

const incomeCategories=['repair_payment','project_payment','service_income','product_sale','consulting','other']
const expenseCategories=['parts','equipment','transport','internet','hosting','software','rent','utilities','marketing','office','maintenance','other']
const deductionCategories=['owner_withdrawal','tax','bank_charges','other']
const methods=['cash','ecocash','bank_transfer','card','paypal','other']
export default function FinancePage(){
 const{profile}=useAuth();const[tab,setTab]=useState('income'),[rows,setRows]=useState([]),[summary,setSummary]=useState({daily:[],monthly:[]}),[modal,setModal]=useState(false),[form,setForm]=useState({amount:'',category:'repair_payment',description:'',payment_method:'cash',reference:'',status:'confirmed'}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('')
 const isAdmin=profile?.role==='admin'
 const load=async()=>{setLoading(true);setError('');const[s,finance]=await Promise.all([getFinanceSummary(),supabase.from(tab).select('*').order(tab==='income'?'income_date':tab==='expenses'?'expense_date':'deduction_date',{ascending:false}).limit(100)]);if(s.errors?.length)setError(s.errors[0]);if(finance.error)setError(x=>x||finance.error.message);setSummary(s);setRows(finance.data||[]);setLoading(false)}
 useEffect(()=>{load()},[tab])
 const config=tab==='income'?{title:'Income',cats:incomeCategories,date:'income_date',desc:'Money actually recognized as received.'}:tab==='expenses'?{title:'Expenses',cats:expenseCategories,date:'expense_date',desc:'Confirmed business costs.'}:{title:'Deductions',cats:deductionCategories,date:'deduction_date',desc:'Owner, tax and bank deductions.'}
 const open=()=>{setForm({amount:'',category:config.cats[0],description:'',payment_method:'cash',reference:'',status:'confirmed'});setMessage('');setError('');setModal(true)}
 const save=async e=>{e.preventDefault();if(!isAdmin)return;setLoading(true);const payload={amount:Number(form.amount||0),category:form.category,description:form.description||null,payment_method:tab==='income'?form.payment_method:null,reference:form.reference||null,status:form.status,recorded_by:(await supabase.auth.getUser()).data.user?.id};const{error:e2}=await supabase.from(tab).insert(payload);if(e2)setError(e2.message);else{setMessage(`${config.title} transaction recorded.`);setModal(false);await load()}setLoading(false)}
 return <div><div className="page-intro"><div><p className="eyebrow">FINANCIAL CONTROL</p><h1>Finance</h1><p className="muted">Authoritative ledgers for income, expenses and deductions. Dashboard totals are derived from confirmed transactions.</p></div><div className="team-actions"><button className="icon-btn" onClick={load}><RefreshCw size={16}/></button>{isAdmin&&<button className="primary" onClick={open}><Plus size={16}/> New transaction</button>}</div></div>{message&&<div className="alert success">{message}</div>}{error&&<div className="alert danger">{error}</div>}
 <div className="metric-grid">{summary.daily.slice(0,1).map(d=><><div className="metric"><span>Latest income</span><strong>{money(d.income)}</strong><small>{dateOnly(d.transaction_date)}</small></div><div className="metric"><span>Latest expenses</span><strong>{money(d.expenses)}</strong><small>{dateOnly(d.transaction_date)}</small></div><div className="metric"><span>Latest deductions</span><strong>{money(d.deductions)}</strong><small>{dateOnly(d.transaction_date)}</small></div><div className="metric"><span>Latest net position</span><strong>{money(d.net_position)}</strong><small>{dateOnly(d.transaction_date)}</small></div></> )}</div>
 <div className="inquiry-tabs">{[['income','Income'],['expenses','Expenses'],['deductions','Deductions']].map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}<strong>{tab===key?rows.length:'↗'}</strong></button>)}</div>
 <section className="panel"><div className="panel-head"><div><p className="eyebrow">{config.title.toUpperCase()} LEDGER</p><h3>{config.desc}</h3></div></div>{loading?<div className="empty">Loading ledger…</div>:rows.length?<div className="table-wrap"><table><thead><tr><th>Date</th><th>Category</th><th>Description</th><th>Amount</th><th>Status</th><th>Reference</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{dateTime(r[config.date])}</td><td><span className="chip">{r.category}</span></td><td>{r.description||'—'}</td><td><strong>{money(r.amount)}</strong></td><td>{r.status}</td><td>{r.reference||'—'}</td></tr>)}</tbody></table></div>:<div className="empty">No transactions in this ledger yet.</div>}</section>
 <div className="section-grid" style={{marginTop:18}}><section className="panel"><div className="panel-head"><div><p className="eyebrow">MONTHLY</p><h3>Financial summary</h3></div></div><div className="table-wrap"><table><thead><tr><th>Month</th><th>Income</th><th>Expenses</th><th>Deductions</th><th>Net</th></tr></thead><tbody>{summary.monthly.map(x=><tr key={x.month_start}><td>{dateOnly(x.month_start)}</td><td>{money(x.income)}</td><td>{money(x.expenses)}</td><td>{money(x.deductions)}</td><td><strong>{money(x.net_position)}</strong></td></tr>)}</tbody></table></div></section><section className="panel"><div className="panel-head"><div><p className="eyebrow">CONTROL</p><h3>Ledger rules</h3></div></div><div className="workflow"><div><span>01</span><p><strong>Income is money received</strong><small>Quotations and repair totals do not become revenue until payment is confirmed.</small></p></div><div><span>02</span><p><strong>Payments are linked</strong><small>Confirmed repair payments create exactly one corresponding income event.</small></p></div><div><span>03</span><p><strong>Net position is derived</strong><small>Income − expenses − deductions. No mutable dashboard counters.</small></p></div></div></section></div>
 {modal&&<div className="modal-backdrop"><form className="modal-card" onSubmit={save}><div className="panel-head"><div><p className="eyebrow">NEW {config.title.toUpperCase()}</p><h3>Record transaction</h3></div><button type="button" className="icon-btn" onClick={()=>setModal(false)}><X size={18}/></button></div><label>Amount<input type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} required/></label><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{config.cats.map(x=><option key={x}>{x}</option>)}</select></label><label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} required/></label>{tab==='income'&&<label>Payment method<select value={form.payment_method} onChange={e=>setForm({...form,payment_method:e.target.value})}>{methods.map(x=><option key={x}>{x}</option>)}</select></label>}<label>Reference<input value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="confirmed">Confirmed</option><option value="voided">Voided</option></select></label><button className="primary full">Record transaction</button></form></div>}
 </div>
}
