import { useEffect, useMemo, useState } from 'react'
import { Check, Pencil, Plus, ReceiptText, RefreshCw, Trash2, X } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { money, dateOnly } from '../lib/data'
import { useAuth } from '../auth/AuthProvider'

const categories=['rent','utilities','airtime','internet','hosting','software','transport','equipment','marketing','office','maintenance','other']
const monthKey=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
const bounds=m=>{const [y,mo]=m.split('-').map(Number);return {start:`${m}-01T00:00:00`,end:new Date(y,mo,1).toISOString(),endDate:new Date(y,mo,1).toISOString().slice(0,10)}}

export default function OperatingCostsPanelV2(){
 const {profile}=useAuth();const isAdmin=profile?.role==='admin';const canWork=isAdmin||profile?.role==='staff'
 const [month,setMonth]=useState(monthKey()),[expenses,setExpenses]=useState([]),[templates,setTemplates]=useState([]),[requests,setRequests]=useState([])
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[modal,setModal]=useState(null)
 const [expense,setExpense]=useState({id:null,amount:'',category:'rent',description:'',date:'',method:'cash',reference:''})
 const [template,setTemplate]=useState({id:null,name:'',amount:'',category:'rent',frequency:'monthly',description:'',active:true})
 const [request,setRequest]=useState({id:null,amount:'',category:'airtime',description:'',needed_date:'',notes:''})
 const b=useMemo(()=>bounds(month),[month])
 const load=async()=>{setLoading(true);setError('');const[e,t,r]=await Promise.all([supabase.from('expenses').select('*').is('repair_id',null).gte('expense_date',b.start).lt('expense_date',b.end).order('expense_date',{ascending:false}),supabase.from('recurring_expense_templates').select('*').order('active',{ascending:false}).order('name'),supabase.from('expense_requisitions').select('*').gte('request_date',`${month}-01`).lt('request_date',b.endDate).order('request_date',{ascending:false})]);const errors=[e.error?.message,t.error?.message,r.error?.message].filter(Boolean);if(errors.length)setError(errors.join(' • '));setExpenses(e.data||[]);setTemplates(t.data||[]);setRequests(r.data||[]);setLoading(false)}
 useEffect(()=>{load()},[month])
 const openExpense=(row=null)=>{setExpense(row?{id:row.id,amount:row.amount,category:row.category,description:row.description||'',date:row.expense_date.slice(0,10),method:row.payment_method||'cash',reference:row.reference||''}:{id:null,amount:'',category:'rent',description:'',date:`${month}-01`,method:'cash',reference:''});setModal('expense')}
 const saveExpense=async e=>{e.preventDefault();if(!isAdmin)return;setLoading(true);const user=await supabase.auth.getUser();const payload={amount:Number(expense.amount),category:expense.category,description:expense.description.trim(),expense_date:new Date(`${expense.date}T12:00:00`).toISOString(),payment_method:expense.method,reference:expense.reference||null,status:'confirmed'};const q=expense.id?supabase.from('expenses').update(payload).eq('id',expense.id):supabase.from('expenses').insert({...payload,recorded_by:user.data.user?.id});const{error}=await q;if(error)setError(error.message);else{setMessage(expense.id?'Operating cost updated.':'Operating cost recorded.');setModal(null);await load()}setLoading(false)}
 const removeExpense=async id=>{if(!isAdmin||!window.confirm('Delete this operating cost?'))return;setLoading(true);const{error}=await supabase.from('expenses').delete().eq('id',id);if(error)setError(error.message);else{setMessage('Operating cost removed.');await load()}setLoading(false)}
 const openTemplate=(row=null)=>{setTemplate(row?{id:row.id,name:row.name,amount:row.amount,category:row.category,frequency:row.frequency,description:row.description,active:row.active}:{id:null,name:'',amount:'',category:'rent',frequency:'monthly',description:'',active:true});setModal('template')}
 const saveTemplate=async e=>{e.preventDefault();if(!isAdmin)return;setLoading(true);const user=await supabase.auth.getUser();const payload={name:template.name.trim(),amount:Number(template.amount),category:template.category,frequency:template.frequency,description:template.description.trim(),active:template.active,created_by:user.data.user?.id};const q=template.id?supabase.from('recurring_expense_templates').update(payload).eq('id',template.id):supabase.from('recurring_expense_templates').insert(payload);const{error}=await q;if(error)setError(error.message);else{setMessage('Recurring cost saved.');setModal(null);await load()}setLoading(false)}
 const recordTemplate=t=>openExpense({amount:t.amount,category:t.category,description:t.description,date:`${month}-01`,method:'cash',reference:`Recurring: ${t.name}`})
 const openRequest=(row=null)=>{setRequest(row?{id:row.id,amount:row.amount_requested,category:row.category,description:row.description,needed_date:row.needed_date||'',notes:row.notes||''}:{id:null,amount:'',category:'airtime',description:'',needed_date:'',notes:''});setModal('request')}
 const saveRequest=async e=>{e.preventDefault();if(!canWork)return;setLoading(true);const user=await supabase.auth.getUser();const payload={amount_requested:Number(request.amount),category:request.category,description:request.description.trim(),needed_date:request.needed_date||null,notes:request.notes||null};const q=request.id?supabase.from('expense_requisitions').update(payload).eq('id',request.id).eq('requested_by',user.data.user?.id):supabase.from('expense_requisitions').insert({...payload,requested_by:user.data.user?.id,status:'submitted'});const{error}=await q;if(error)setError(error.message);else{setMessage(request.id?'Requisition updated.':'Requisition submitted.');setModal(null);await load()}setLoading(false)}
 const reviewRequest=async(row,status)=>{if(!isAdmin)return;setLoading(true);const user=await supabase.auth.getUser();const{error}=await supabase.from('expense_requisitions').update({status,approved_by:user.data.user?.id,approved_at:new Date().toISOString()}).eq('id',row.id);if(error)setError(error.message);else{setMessage(`Requisition ${status}.`);await load()}setLoading(false)}
 const fulfillRequest=async row=>{if(!isAdmin)return;setLoading(true);const user=await supabase.auth.getUser();const{data:created,error:e}=await supabase.from('expenses').insert({amount:Number(row.amount_requested),category:row.category,description:row.description,expense_date:new Date(`${month}-01T12:00:00`).toISOString(),payment_method:'cash',reference:`Requisition ${row.id.slice(0,8)}`,recorded_by:user.data.user?.id,status:'confirmed'}).select('id').single();if(e){setError(e.message);setLoading(false);return}const{error}=await supabase.from('expense_requisitions').update({status:'fulfilled',fulfilled_at:new Date().toISOString(),expense_id:created.id}).eq('id',row.id);if(error)setError(error.message);else{setMessage('Requisition fulfilled and recorded as an expense.');await load()}setLoading(false)}
 const total=expenses.reduce((s,x)=>s+Number(x.amount||0),0),approved=requests.filter(x=>x.status==='approved').reduce((s,x)=>s+Number(x.amount_requested||0),0),pending=requests.filter(x=>x.status==='submitted').reduce((s,x)=>s+Number(x.amount_requested||0),0)
 return <div className="workspace-section">
  <div className="page-intro"><div><p className="eyebrow">OPERATING COSTS</p><h2>Monthly business costs</h2><p className="muted">Record actual costs throughout the month. Recurring amounts are editable starting points, not fixed charges.</p></div><div className="team-actions"><button className="icon-btn" onClick={load} title="Refresh"><RefreshCw size={16}/></button>{canWork&&<button className="secondary" onClick={()=>openRequest()}><ReceiptText size={15}/> New requisition</button>}{isAdmin&&<button className="primary" onClick={()=>openExpense()}><Plus size={15}/> Record cost</button>}</div></div>
  {message&&<div className="alert success">{message}</div>}{error&&<div className="alert danger">{error}</div>}
  <div className="workspace-grid workspace-grid-four"><div className="metric"><span>Actual costs</span><strong>{money(total)}</strong><small>{month}</small></div><div className="metric"><span>Approved requests</span><strong>{money(approved)}</strong><small>Not counted until fulfilled</small></div><div className="metric"><span>Pending requests</span><strong>{money(pending)}</strong><small>Awaiting approval</small></div><div className="metric"><span>Recurring costs</span><strong>{templates.filter(x=>x.active).length}</strong><small>Editable templates</small></div></div>
  <section className="panel"><div className="panel-head"><div><p className="eyebrow">MONTHLY RECORD</p><h3>Actual operating costs</h3><p className="muted">These entries are part of the authoritative expense ledger and therefore flow into the business position.</p></div><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></div>{loading?<div className="empty">Loading costs…</div>:expenses.length?<div className="table-wrap"><table><thead><tr><th>Date</th><th>Category</th><th>Description</th><th>Amount</th><th>Reference</th>{isAdmin&&<th></th>}</tr></thead><tbody>{expenses.map(x=><tr key={x.id}><td>{dateOnly(x.expense_date)}</td><td><span className="chip">{x.category}</span></td><td>{x.description}</td><td><strong>{money(x.amount)}</strong></td><td>{x.reference||'—'}</td>{isAdmin&&<td><div className="team-actions"><button className="icon-btn" onClick={()=>openExpense(x)} title="Edit"><Pencil size={14}/></button><button className="icon-btn" onClick={()=>removeExpense(x.id)} title="Delete"><Trash2 size={14}/></button></div></td>}</tr>)}</tbody></table></div>:<div className="empty">No operating costs recorded for this month.</div>}</section>
  <section className="panel"><div className="panel-head"><div><p className="eyebrow">RECURRING COSTS</p><h3>Regular business costs</h3><p className="muted">Use the template to start the month, then edit the actual expense if the bill changes.</p></div>{isAdmin&&<button className="secondary" onClick={()=>openTemplate()}><Plus size={15}/> Add recurring cost</button>}</div>{templates.length?<div className="table-wrap"><table><thead><tr><th>Cost</th><th>Category</th><th>Frequency</th><th>Amount</th><th>Status</th>{isAdmin&&<th></th>}</tr></thead><tbody>{templates.map(x=><tr key={x.id}><td><strong>{x.name}</strong><br/><small>{x.description}</small></td><td>{x.category}</td><td>{x.frequency}</td><td>{money(x.amount)}</td><td>{x.active?'Active':'Paused'}</td>{isAdmin&&<td><div className="team-actions"><button className="secondary" onClick={()=>recordTemplate(x)}>Record this month</button><button className="icon-btn" onClick={()=>openTemplate(x)} title="Edit"><Pencil size={14}/></button></div></td>}</tr>)}</tbody></table></div>:<div className="empty">No recurring costs set up.</div>}</section>
  <section className="panel"><div className="panel-head"><div><p className="eyebrow">REQUISITIONS</p><h3>Monthly spending requests</h3><p className="muted">Requests stay separate from expenses until an admin approves and records the actual spend.</p></div></div>{requests.length?<div className="table-wrap"><table><thead><tr><th>Date</th><th>Request</th><th>Category</th><th>Amount</th><th>Status</th><th></th></tr></thead><tbody>{requests.map(x=><tr key={x.id}><td>{dateOnly(x.request_date)}</td><td>{x.description}</td><td>{x.category}</td><td>{money(x.amount_requested)}</td><td>{x.status}</td><td><div className="team-actions">{x.status==='submitted'&&isAdmin&&<><button className="secondary" onClick={()=>reviewRequest(x,'approved')}><Check size={14}/> Approve</button><button className="icon-btn" onClick={()=>reviewRequest(x,'rejected')} title="Reject"><X size={14}/></button></>}{x.status==='approved'&&isAdmin&&<button className="secondary" onClick={()=>fulfillRequest(x)}>Record expense</button>}{x.status==='submitted'&&x.requested_by===profile?.id&&<button className="icon-btn" onClick={()=>openRequest(x)} title="Edit"><Pencil size={14}/></button>}</div></td></tr>)}</tbody></table></div>:<div className="empty">No requisitions for this month.</div>}</section>
  {modal==='expense'&&<div className="modal-backdrop"><form className="modal-card" onSubmit={saveExpense}><div className="panel-head"><div><p className="eyebrow">OPERATING COST</p><h3>{expense.id?'Edit cost':'Record cost'}</h3></div><button type="button" className="icon-btn" onClick={()=>setModal(null)}><X size={18}/></button></div><label>Amount<input type="number" min="0.01" step="0.01" value={expense.amount} onChange={e=>setExpense({...expense,amount:e.target.value})} required/></label><label>Date<input type="date" value={expense.date} onChange={e=>setExpense({...expense,date:e.target.value})} required/></label><label>Category<select value={expense.category} onChange={e=>setExpense({...expense,category:e.target.value})}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label>Description<textarea value={expense.description} onChange={e=>setExpense({...expense,description:e.target.value})} required/></label><label>Payment method<select value={expense.method} onChange={e=>setExpense({...expense,method:e.target.value})}><option>cash</option><option>ecocash</option><option>bank_transfer</option><option>card</option><option>paypal</option><option>other</option></select></label><label>Reference<input value={expense.reference} onChange={e=>setExpense({...expense,reference:e.target.value})}/></label><button className="primary full" disabled={loading}>Save cost</button></form></div>}
  {modal==='template'&&<div className="modal-backdrop"><form className="modal-card" onSubmit={saveTemplate}><div className="panel-head"><div><p className="eyebrow">RECURRING COST</p><h3>{template.id?'Edit recurring cost':'Add recurring cost'}</h3></div><button type="button" className="icon-btn" onClick={()=>setModal(null)}><X size={18}/></button></div><label>Name<input value={template.name} onChange={e=>setTemplate({...template,name:e.target.value})} required/></label><label>Amount<input type="number" min="0.01" step="0.01" value={template.amount} onChange={e=>setTemplate({...template,amount:e.target.value})} required/></label><label>Category<select value={template.category} onChange={e=>setTemplate({...template,category:e.target.value})}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label>Frequency<select value={template.frequency} onChange={e=>setTemplate({...template,frequency:e.target.value})}><option>monthly</option><option>weekly</option></select></label><label>Description<textarea value={template.description} onChange={e=>setTemplate({...template,description:e.target.value})} required/></label><button className="primary full" disabled={loading}>Save recurring cost</button></form></div>}
  {modal==='request'&&<div className="modal-backdrop"><form className="modal-card" onSubmit={saveRequest}><div className="panel-head"><div><p className="eyebrow">MONTHLY REQUISITION</p><h3>{request.id?'Edit requisition':'New requisition'}</h3></div><button type="button" className="icon-btn" onClick={()=>setModal(null)}><X size={18}/></button></div><label>Amount<input type="number" min="0.01" step="0.01" value={request.amount} onChange={e=>setRequest({...request,amount:e.target.value})} required/></label><label>Category<select value={request.category} onChange={e=>setRequest({...request,category:e.target.value})}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label>What is needed?<textarea value={request.description} onChange={e=>setRequest({...request,description:e.target.value})} required/></label><label>Needed by<input type="date" value={request.needed_date} onChange={e=>setRequest({...request,needed_date:e.target.value})}/></label><label>Notes<textarea value={request.notes} onChange={e=>setRequest({...request,notes:e.target.value})}/></label><button className="primary full" disabled={loading}>Submit requisition</button></form></div>}
 </div>
}
