import { useEffect, useMemo, useState } from 'react'
import { CheckCircle2, ChevronRight, FolderKanban, Plus, RefreshCw, Search, UserRound, X, ArrowUpRight, CircleDot } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { supabase } from '../lib/supabase'

const CONFIG={
 projects:{eyebrow:'DELIVERY CONTROL',title:'Projects',description:'Turn confirmed client work into clear, trackable delivery.',columns:['title','status','start_date','end_date'],fields:[['title','Title','text',true],['description','Description','textarea',false],['owner_id','Client','client',true],['status','Status','projectStatus',true],['start_date','Start date','date',false],['end_date','End date','date',false]]},
 services:{eyebrow:'OFFERINGS',title:'Services',description:'Manage the services presented by the public website.',columns:['name','slug','is_active','sort_order'],fields:[['name','Name','text',true],['slug','Slug','text',true],['description','Description','textarea',false],['icon','Icon','text',false],['sort_order','Order','number',false],['is_active','Active','boolean',false]]},
 tickets:{eyebrow:'SUPPORT',title:'Tickets',description:'Own the support queue, assign work and keep clients informed.',columns:['subject','status','priority','assignee.full_name'],fields:[['subject','Subject','text',true],['client_id','Client','client',true],['assignee_id','Assignee','staff',false],['priority','Priority','priority',true],['status','Status','ticketStatus',true]]}}
const initial=table=>Object.fromEntries((CONFIG[table]?.fields||[]).map(([key])=>[key,key==='status'?(table==='tickets'?'open':'planned'):key==='priority'?'normal':key==='is_active'?true:'']))
const labelize=value=>String(value||'').replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase())
const formatValue=value=>value===null||value===undefined||value===''?'—':typeof value==='boolean'?(value?'Yes':'No'):String(value)
const formatDate=value=>value?new Date(value).toLocaleString([],{dateStyle:'medium',timeStyle:'short'}):'—'
const projectStatusClass=value=>value==='active'?'success':value==='on_hold'?'warning':value==='completed'?'success':'neutral'
const projectFilters=[['all','All'],['active','Active'],['planned','Planned'],['on_hold','On hold'],['completed','Completed']]

export default function OperationalResourcePage({table}){
 const config=CONFIG[table],navigate=useNavigate();const[rows,setRows]=useState([]),[clients,setClients]=useState([]),[staff,setStaff]=useState([]),[assignedWork,setAssignedWork]=useState([]),[tasks,setTasks]=useState([]);const[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[selected,setSelected]=useState(null),[modalOpen,setModalOpen]=useState(false),[form,setForm]=useState(()=>initial(table)),[message,setMessage]=useState(''),[error,setError]=useState('')
 const load=async()=>{setLoading(true);setError('');let query=table==='projects'?supabase.from('projects').select('id,title,description,status,start_date,end_date,owner_id,created_at,updated_at,owner:profiles!projects_owner_id_fkey(id,full_name,company)').order('updated_at',{ascending:false}):table==='tickets'?supabase.from('tickets').select('id,subject,status,priority,client_id,assignee_id,created_at,updated_at,client:profiles!tickets_client_id_fkey(id,full_name),assignee:profiles!tickets_assignee_id_fkey(id,full_name)').order('updated_at',{ascending:false}):supabase.from(table).select('*').order('updated_at',{ascending:false});const requests=[query,supabase.from('profiles').select('id,full_name,role,company').eq('role','client').order('full_name'),supabase.from('profiles').select('id,full_name,role').in('role',['staff','admin']).order('full_name')];if(table==='projects'){requests.push(supabase.from('inquiries').select('id,name,email,service,budget,status,assigned_to,customer_id,created_at,updated_at,assigned:profiles!inquiries_assigned_to_fkey(id,full_name)').not('assigned_to','is',null).is('project_id',null).in('status',['new','contacted','qualified']).order('updated_at',{ascending:false}));requests.push(supabase.from('project_tasks').select('id,project_id,status'))}const[main,clientRes,staffRes,workRes,tasksRes]=await Promise.all(requests);if(main.error)setError(main.error.message);else setRows(main.data||[]);if(clientRes.error)setError(x=>x||clientRes.error.message);else setClients(clientRes.data||[]);if(staffRes.error)setError(x=>x||staffRes.error.message);else setStaff(staffRes.data||[]);if(table==='projects'){if(workRes?.error)setError(x=>x||workRes.error.message);else setAssignedWork(workRes?.data||[]);if(tasksRes?.error)setError(x=>x||tasksRes.error.message);else setTasks(tasksRes?.data||[])}setLoading(false)}
 useEffect(()=>{load()},[table])
 const projectStats=useMemo(()=>({active:rows.filter(x=>x.status==='active').length,planned:rows.filter(x=>x.status==='planned').length,completed:rows.filter(x=>x.status==='completed').length,onHold:rows.filter(x=>x.status==='on_hold').length}),[rows])
 const taskByProject=useMemo(()=>tasks.reduce((acc,t)=>{const key=t.project_id;(acc[key] ||= {total:0,done:0,open:0});acc[key].total+=1;if(t.status==='completed')acc[key].done+=1;else acc[key].open+=1;return acc},{}),[tasks])
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return rows.filter(row=>{const matchesFilter=table!=='projects'||filter==='all'||row.status===filter;const matchesSearch=!q||JSON.stringify(row).toLowerCase().includes(q);return matchesFilter&&matchesSearch})},[rows,search,filter,table])
 const openCreate=()=>{setSelected(null);setForm(initial(table));setMessage('');setError('');setModalOpen(true)}
 const openEdit=row=>{setSelected(row);const next=initial(table);for(const[key]of config.fields)next[key]=row[key]??next[key];setForm(next);setMessage('');setError('');setModalOpen(true)}
 const save=async e=>{e.preventDefault();setSaving(true);setError('');setMessage('');const payload={...form};Object.keys(payload).forEach(k=>{if(payload[k]==='')payload[k]=null});if(table==='services'&&!payload.slug)payload.slug=String(payload.name||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');const result=selected?await supabase.from(table).update(payload).eq('id',selected.id).select().single():await supabase.from(table).insert(payload).select().single();if(result.error)setError(result.error.message);else{setMessage(selected?'Record updated successfully.':'Record created successfully.');setModalOpen(false);setForm(initial(table));await load()}setSaving(false)}
 if(!config)return null
 const taskTotal=tasks.length,taskDone=tasks.filter(x=>x.status==='completed').length
 return <div className={table==='projects'?'workspace workspace-projects':'workspace'}>
  <div className="page-intro"><div><p className="eyebrow">{config.eyebrow}</p><h1>{config.title}</h1><p className="muted">{config.description}</p></div><div className="team-actions"><button className="icon-btn" onClick={load} title="Refresh"><RefreshCw size={16}/></button><button className="primary" onClick={openCreate}><Plus size={16}/> New {table==='projects'?'project':table==='tickets'?'ticket':'service'}</button></div></div>
  {message&&<div className="alert success"><CheckCircle2 size={15}/> {message}</div>}{error&&<div className="alert danger">{error}</div>}
  {table==='projects'&&<>
   <section className="project-command"><div><p className="eyebrow">DELIVERY PIPELINE</p><h3>Move work from confirmed to delivered</h3><p className="muted">Projects are delivery records. Client inquiries become projects before execution begins.</p></div><div className="project-command-side"><span>Task completion</span><strong>{taskTotal?`${Math.round((taskDone/taskTotal)*100)}%`:'—'}</strong><small>{taskDone} of {taskTotal} tasks completed</small></div></section>
   <div className="project-summary"><div className="metric"><span>Active</span><strong>{projectStats.active}</strong><small>Delivery in motion</small></div><div className="metric"><span>Planned</span><strong>{projectStats.planned}</strong><small>Confirmed, not started</small></div><div className="metric"><span>On hold</span><strong>{projectStats.onHold}</strong><small>Needs a decision</small></div><div className="metric"><span>Completed</span><strong>{projectStats.completed}</strong><small>Delivered work</small></div></div>
   <section className="panel project-incoming"><div className="panel-head"><div><p className="eyebrow">INCOMING WORK</p><h3>Assigned inquiries</h3><p className="muted">The handoff point between client work and delivery.</p></div><div className="section-icon"><FolderKanban size={18}/></div></div>{assignedWork.length?<div className="table-wrap"><table><thead><tr><th>Client</th><th>Service</th><th>Stage</th><th>Owner</th><th></th></tr></thead><tbody>{assignedWork.map(item=><tr key={item.id} className="clickable-row" onClick={()=>navigate('/inquiries')}><td><strong>{item.name||'Unnamed client'}</strong><small className="table-sub">{item.email}</small></td><td>{item.service||'General inquiry'}</td><td><span className="chip">{labelize(item.status)}</span></td><td><span className="inline-user"><UserRound size={13}/>{item.assigned?.full_name||'Assigned staff'}</span></td><td><span className="row-action">Open <ArrowUpRight size={13}/></span></td></tr>)}</tbody></table></div>:<div className="empty-state-rich"><div className="empty-icon"><CircleDot size={20}/></div><div><strong>No incoming work right now</strong><p>Assigned client inquiries will appear here before they are converted into delivery projects.</p></div><button className="secondary" onClick={()=>navigate('/inquiries')}>View inquiries <ArrowUpRight size={14}/></button></div>}</section>
   <div className="workspace-tabs project-tabs">{projectFilters.map(([key,label])=><button key={key} className={filter===key?'active':''} onClick={()=>setFilter(key)}>{label}<span>{key==='all'?rows.length:key==='active'?projectStats.active:key==='planned'?projectStats.planned:key==='on_hold'?projectStats.onHold:projectStats.completed}</span></button>)}</div>
  </>}
  <section className="panel"><div className="panel-head"><div><p className="eyebrow">{table==='projects'?'DELIVERY RECORDS':'LIVE DATABASE'}</p><h3>{loading?'Loading…':`${filtered.length} ${table==='projects'?'project':table==='tickets'?'ticket':'service'}${filtered.length===1?'':'s'}`}</h3><p className="muted">{table==='projects'?'Open a project to manage delivery details, team, files and activity.':'Live operational records.'}</p></div><div className="search-box"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={table==='projects'?'Search projects':'Search records'}/></div></div>{loading?<div className="empty">Loading live records…</div>:filtered.length===0?<div className="empty-state-rich database-empty"><div className="empty-icon"><FolderKanban size={20}/></div><div><strong>{search?'No matching records':`No ${table==='projects'?'project':'operational'} records yet`}</strong><p>{search?'Try another search or filter.':table==='projects'?'Create a project when confirmed client work is ready for delivery.':'Create the first live record.'}</p></div>{!search&&<button className="primary" onClick={openCreate}><Plus size={14}/> Create record</button>}</div>:<div className="table-wrap"><table><thead><tr>{config.columns.map(c=><th key={c}>{labelize(c)}</th>)}{table==='projects'&&<th>Tasks</th>}<th></th></tr></thead><tbody>{filtered.map(row=>{const task=taskByProject[row.id]||{total:0,done:0,open:0};return <tr key={row.id} className="clickable-row" onClick={()=>table==='projects'?navigate(`/projects/${row.id}`):openEdit(row)}>{config.columns.map(c=><td key={c}>{c==='status'&&table==='projects'?<span className={`chip ${projectStatusClass(row[c])}`}>{labelize(row[c])}</span>:c==='start_date'||c==='end_date'?formatDate(row[c]):formatValue(c.includes('.')?c.split('.').reduce((o,k)=>o?.[k],row):row[c])}</td>)}{table==='projects'&&<td>{task.total?`${task.done}/${task.total}`:'—'}</td>}<td><ChevronRight size={15}/></td></tr>})}</tbody></table></div>}</section>
  {modalOpen&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setModalOpen(false)}><form className="modal-card operational-form" onSubmit={save}><div className="panel-head"><div><p className="eyebrow">{selected?'EDIT RECORD':'NEW RECORD'}</p><h3>{selected?`Edit ${config.title.slice(0,-1)}`:`Create ${table==='projects'?'project':table==='tickets'?'ticket':'service'}`}</h3></div><button type="button" className="icon-btn" onClick={()=>setModalOpen(false)}><X size={18}/></button></div>{config.fields.map(([key,label,type,required])=>{if(type==='projectStatus')return <label key={key}>{label}<select value={form[key]??'planned'} onChange={e=>setForm({...form,[key]:e.target.value})} required={required}><option value="planned">Planned</option><option value="active">Active</option><option value="on_hold">On hold</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></label>;if(type==='ticketStatus')return <label key={key}>{label}<select value={form[key]??'open'} onChange={e=>setForm({...form,[key]:e.target.value})} required={required}><option value="open">Open</option><option value="in_progress">In progress</option><option value="waiting">Waiting</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select></label>;if(type==='priority')return <label key={key}>{label}<select value={form[key]??'normal'} onChange={e=>setForm({...form,[key]:e.target.value})} required={required}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></label>;if(type==='textarea')return <label key={key}>{label}<textarea value={form[key]??''} onChange={e=>setForm({...form,[key]:e.target.value})} required={required}/></label>;if(type==='boolean')return <label key={key} className="checkbox-field"><input type="checkbox" checked={!!form[key]} onChange={e=>setForm({...form,[key]:e.target.checked})}/>{label}</label>;if(type==='client')return <label key={key}>{label}<select value={form[key]??''} onChange={e=>setForm({...form,[key]:e.target.value})} required={required}><option value="">Select client…</option>{clients.map(x=><option key={x.id} value={x.id}>{x.full_name||'Unnamed'}{x.company?` — ${x.company}`:''}</option>)}</select></label>;if(type==='staff')return <label key={key}>{label}<select value={form[key]??''} onChange={e=>setForm({...form,[key]:e.target.value})}><option value="">Unassigned</option>{staff.map(x=><option key={x.id} value={x.id}>{x.full_name||x.role}</option>)}</select></label>;return <label key={key}>{label}<input type={type} value={form[key]??''} onChange={e=>setForm({...form,[key]:e.target.value})} required={required}/></label>})}<button className="primary full" disabled={saving}>{saving?'Saving…':selected?'Save changes':'Create record'}</button></form></div>}
 </div>
}
