import { useEffect, useMemo, useState } from 'react'
import { Check, Pencil, Plus, ReceiptText, RefreshCw, Trash2, X } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { money, dateOnly } from '../lib/data'
import { useAuth } from '../auth/AuthProvider'

const categories=['rent','utilities','airtime','internet','hosting','software','transport','equipment','marketing','office','maintenance','other']
const frequencies=['monthly','weekly']
const requisitionStatuses=['submitted','approved','rejected','fulfilled','cancelled']
const monthKey=(date=new Date())=>{const y=date.getFullYear();const m=String(date.getMonth()+1).padStart(2,'0');return `${y}-${m}`}
const monthBounds=month=>{const [y,m]=month.split('-').map(Number);return {start:`${y}-${String(m).padStart(2,'0')}-01T00:00:00`,end:new Date(y,m,1).toISOString()}}

export default function OperatingCostsPanel(){
 const {profile}=useAuth(); const isAdmin=profile?.role==='admin'; const canWork=profile?.role==='admin'||profile?.role==='staff'
 const [month,setMonth]=useState(monthKey()),[expenses,setExpenses]=useState([]),[templates,setTemplates]=useState([]),[requisitions,setRequisitions]=useState([])
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[modal,setModal]=useState(null)
 const [expenseForm,setExpenseForm]=useState({id:null,amount:'',category:'rent',description:'',expense_date:'',payment_method:'cash',reference:''})
 const [templateForm,setTemplateForm]=useState({id:null,name:'',category:'rent',description:'',amount:'',frequency:'monthly',active:true})
 const [reqForm,setReqForm]=useState({id:null,category:'airtime',description:'',amount_requested:'',needed_date:'',notes:''})
 const bounds=useMemo(()=>monthBounds(month),[month])
 const load=async()=>{
  setLoading(true);setError('')
  const [e,t,r]=await Promise.all([
   supabase.from('expenses').select('*').is('repair_id',null).gte('expense_date',bounds.start).lt('expense_date',bounds.end).order('expense_date',{ascending:false}),
   supabase.from('recurring_expense_templates').select('*').order('active',{ascending:false}).order('name'),
   supabase.from('expense_requisitions').select('*').gte('request_date',`${month}-01`).lt('request_date',monthBounds(month).end.slice(0,10)).order('request_date',{ascending:false})
  ])
  const errors=[e.error?.message,t.error?.message,r.error?.message].filter(Boolean); if(errors.length)setError(errors.join(' • '))
  setExpenses(e.data||[]);setTemplates(t.data||[]);setRequisitions(r.data||[]);setLoading(false)
 }
 useEffect(()=>{load()},[month])
 const openExpense=(row=null)=>{setExpenseForm(row?{id:row.id,amount:row.amount,category:row.category,description:row.description||'',expense_date:row.expense_date?.slice(0,10)||month+'-01',payment_method:row.payment_method||'cash',reference:row.reference||''}:{id:null,amount:'',category:'rent',description:'',expense_date:month+'-01',payment_method:'cash',reference:''});setModal('expense');setMessage('')}
 const saveExpense=async e=>{e.preventDefault();if(!isAdmin)return;setLoading(true);const payload={amount:Number(expenseForm.amount),category:expenseForm.category,description:expenseForm.description.trim(),expense_date:new Date(`${expenseForm.expense_date}T12:00:00`).toISOString(),payment_method:expenseForm.payment_method||null,reference:expenseForm.reference||null,status:'confirmed'};const q=expenseForm.id?supabase.from('expenses').update(payload).eq('id',expenseForm.id):supabase.from('expenses').insert({...payload,recorded_by:(await supabase.auth.getUser()).data.user?.id});const {error}=await q;if(error)setError(error.message);else{setMessage(expenseForm.id?'Operating cost updated.':'Operating cost recorded.');setModal(null);await load()}setLoading(false)}
 const deleteExpense=async id=>{if(!isAdmin||!confirm('Delete this operating cost?'))return;setLoading(true);const {error}=await supabase.from('expenses').delete().eq('id',id);if(error)setError(error.message);else{setMessage('Operating cost removed.');await load()}setLoading(false)}
 const openTemplate=(row=null)=>{setTemplateForm(row?{id:row.id,name:row.name,category:row.category,description:row.description,amount:row.amount,frequency:row.frequency,active:row.active}:{id:null,name:'',category:'rent',description:'',amount:'',frequency:'monthly',active:true});setModal('template');setMessage('')}
 const saveTemplate=async e=>{e.preventDefault();if(!isAdmin)return;setLoading(true);const user=await supabase.auth.getUser();const payload={name:templateForm.name.trim(),category:templateForm.category,description:templateForm.description.trim(),amount:Number(templateForm.amount),frequency:templateForm.frequency,active:templateForm.active,created_by:user.data.user?.id};const q=templateForm.id?supabase.from('recurring_expense_templates').update(payload).eq('id',templateForm.id):supabase.from('recurring_expense_templates').insert(payload);const {error}=await q;if(error)setError(error.message);else{setMessage('Recurring cost template saved.');setModal(null);await load()}setLoading(false)}
 const postTemplate=async t=>{if(!isAdmin)return;openExpense({amount:t.amount,category:t.category,description:t.description,expense_date:month+'-01',payment_method:'cash',reference:`Recurring: ${t.name}`})}
 const openReq=(row=null)=>{setReqForm(row?{id:row.id,category:row.category,description:row.description,amount_requested:row.amount_requested,needed_date:row.needed_date||'',notes:row.notes||''}:{id:null,category:'airtime',description:'',amount_requested:'',needed_date:'',notes:''});setModal('requisition');setMessage('')}
 const saveReq=async e=>{e.preventDefault();if(!canWork)return;setLoading(true);const user=await supabase.auth.getUser();const payload={category:reqForm.category,description:reqForm.description.trim(),amount_requested:Number(reqForm.amount_requested),needed_date:reqForm.needed_date||null,notes:reqForm.notes||null};const q=reqForm.id?supabase.from('expense_requisitions').update(payload).eq('id',reqForm.id).eq('requested_by',user.data.user?.id):supabase.from('expense_requisitions').insert({...payload,requested_by:user.data.user?.id,status:'submitted'});const {error}=await q;if(error)setError(error.message);else{setMessage(reqForm.id?'Requisition updated.':'Requisition submitted.');setModal(null);await load()}setLoading(false)}
 const approve=async(id,status)=>{if(!isAdmin)return;setLoading(true);const {error}=await supabase.from('expense_requisitions').update({status,approved_by:(await supabase.auth.getUser()).data.user?.id,approved_at:new Date().toISOString()}).eq('id',id);if(error)setError(error.message);else{setMessage(`Requisition ${status}.`);await load()}setLoading(false)}
 const fulfill=async row=>{if(!isAdmin)return;openExpense({amount:row.amount_requested,category:row.category,description:row.description,expense_date:month+'-01',payment_method:'cash',reference:`Requisition ${row.id.slice(0,8)}`});setReqForm({...reqForm,id:row.id})}
 const saveFulfilledLink=async()=>{if(!reqForm.id)return;await supabase.from('expense_requisitions').update({status:'fulfilled',fulfilled_at:new Date().toISOString()}).eq('id',reqForm.id);setReqForm({...reqForm,id:null})}
 const total=expenses.reduce((sum,x)=>sum+Number(x.amount||0),0)
 const approved=requisitions.filter(x=>x.status==='approved').reduce((sum,x)=>sum+Number(x.amount_requested||0),0)
 const pending=requisitions.filter(x=>x.status==='submitted').reduce((sum,x)=>sum+Number(x.amount_requested||0),0)
 const closeExpense=async()=>{setModal(null);if(reqForm.id)await saveFulfilledLink();await load()}
 return <div className="workspace-section">
  <div className="page-intro"><div><p className="eyebrow">OPERATING COSTS</p><h2>Monthly business costs</h2><p className="muted">Record what the business actually spends. Recurring amounts are starting points, not fixed values.</p></div><div className="team-actions"><button className="icon-btn" onClick={load} title="Refresh"><RefreshCw size={16}/></button>{canWork&&<button className="primary" onClick={()=>openReq()}><ReceiptText size={16}/> New requisition</button>}{isAdmin&&<button className="primary" onClick={()=>openExpense()}><Plus size={16}/> Record cost</button>}</div></div>
  {message&&<div className="alert success">{message}</div>}{error&&<div className="alert danger">{error}</div>}
  <div className="workspace-grid workspace-grid-four"><div className="metric"><span>Actual costs</span><strong>{money(total)}</strong><small>{month}</small></div><div className="metric"><span>Approved requests</span><strong>{money(approved)}</strong><small>Not counted as expense until recorded</small></div><div className="metric"><span>Pending requests</span><strong>{money(pending)}</strong><small>Awaiting approval</small></div><div className="metric"><span>Recurring plans</span><strong>{templates.filter(x=>x.active).length}</strong><small>Editable templates</small></div></div>
  <section className="panel"><div className="panel-head"><div><p className="eyebrow">MONTH</p><h3>Actual operating costs</h3><p className="muted">These entries flow into the existing Finance monthly position.</p></div><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></div>{loading?<div className="empty">Loading costs…</div>:expenses.length?<div className="table-wrap"><table><thead><tr><th>Date</th><th>Category</th><th>Description</th><th>Amount</th><th>Reference</th>{isAdmin&&<th></th>}</tr></thead><tbody>{expenses.map(r=><tr key={r.id}><td>{dateOnly(r.expense_date)}</td><td><span className="chip">{r.category}</span></td><td>{r.description}</td><td><strong>{money(r.amount)}</strong></td><td>{r.reference||'—'}</td>{isAdmin&&<td><div className="team-actions"><button className="icon-btn" onClick={()=>openExpense(r)} title="Edit"><Pencil size={14}/></button><button className="icon-btn" onClick={()=>deleteExpense(r.id)} title="Delete"><Trash2 size={14}/></button></div></td>}</tr>)}</tbody></table></div>:<div className="empty">No operating costs recorded for this month.</div>}</section>
  <section className="panel"><div className="panel-head"><div><p className="eyebrow">RECURRING COSTS</p><h3>Regular business costs</h3><p className="muted">Templates do not change the accounts. Use “Record this month” to post the actual amount, then edit it if the real bill differs.</p></div>{isAdmin&&<button className="secondary" onClick={()=>openTemplate()}><Plus size={15}/> Add recurring cost</button>}</div>{templates.length?<div className="table-wrap"><table><thead><tr><th>Cost</th><th>Category</th><th>Frequency</th><th>Amount</th><th>Status</th>{isAdmin&&<th></th>}</tr></thead><tbody>{templates.map(t=><tr key={t.id}><td><strong>{t.name}</strong><br/><small>{t.description}</small></td><td>{t.category}</td><td>{t.frequency}</td><td>{money(t.amount)}</td><td>{t.active?'Active':'Paused'}</td>{isAdmin&&<td><div className="team-actions"><button className="secondary" onClick={()=>postTemplate(t)}>Record this month</button><button className="icon-btn" onClick={()=>openTemplate(t)} title="Edit"><Pencil size={14}/></button></div></td>}</tr>)}</tbody></table></div>:<div className="empty">No recurring costs set up.</div>}</section>
  <section className="panel"><div className="panel-head"><div><p className="eyebrow">REQUISITIONS</p><h3>Requests for business spending</h3><p className="muted">Keep requests during the month, then convert approved requests into real expenses.</p></div></div>{requisitions.length?<div className="table-wrap"><table><thead><tr><th>Date</th><th>Request</th><th>Category</th><th>Amount</th><th>Status</th><th></th></tr></thead><tbody>{requisitions.map(r=><tr key={r.id}><td>{dateOnly(r.request_date)}</td><td>{r.description}</td><td>{r.category}</td><td>{money(r.amount_requested)}</td><td>{r.status}</td><td><div className="team-actions">{r.status==='submitted'&&isAdmin&&<><button className="secondary" onClick={()=>approve(r.id,'approved')}><Check size={14}/> Approve</button><button className="icon-btn" onClick={()=>approve(r.id,'rejected')} title="Reject"><X size={14}/></button></>}{r.status==='approved'&&isAdmin&&<button className="secondary" onClick={()=>fulfill(r)}>Record expense</button>}{r.status==='submitted'&&r.requested_by===profile?.id&&<button className="icon-btn" onClick={()=>openReq(r)} title="Edit"><Pencil size={14}/></button>}</div></td></tr>)}</tbody></table></div>:<div className="empty">No requisitions for this month.</div>}</section>
  {modal==='expense'&&<div className="modal-backdrop"><form className="modal-card" onSubmit={async e=>{await saveExpense(e);if(reqForm.id&&!expenseForm.id&&!error)await saveFulfilledLink()}}><div className="panel-head"><div><p className="eyebrow">OPERATING COST</p><h3>{expenseForm.id?'Edit cost':'Record cost'}</h3></div><button type="button" className="icon-btn" onClick={()=>setModal(null)}><X size={18}/></button></div><label>Amount<input type="number" min="0.01" step="0.01" value={expenseForm.amount} onChange={e=>setExpenseForm({...expenseForm,amount:e.target.value})} required/></label><label>Date<input type="date" value={expenseForm.expense_date} onChange={e=>setExpenseForm({...expenseForm,expense_date:e.target.value})} required/></label><label>Category<select value={expenseForm.category} onChange={e=>setExpenseForm({...expenseForm,category:e.target.value})}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label>Description<textarea value={expenseForm.description} onChange={e=>setExpenseForm({...expenseForm,description:e.target.value})} required/></label><label>Payment method<select value={expenseForm.payment_method} onChange={e=>setExpenseForm({...expenseForm,payment_method:e.target.value})}><option>cash</option><option>ecocash</option><option>bank_transfer</option><option>card</option><option>paypal</option><option>other</option></select></label><label>Reference<input value={expenseForm.reference} onChange={e=>setExpenseForm({...expenseForm,reference:e.target.value})}/></label><button className="primary full" disabled={loading}>Save cost</button></form></div>}
  {modal==='template'&&<div className="modal-backdrop"><form className="modal-card" onSubmit={saveTemplate}><div className="panel-head"><div><p className="eyebrow">RECURRING COST</p><h3>{templateForm.id?'Edit recurring cost':'Add recurring cost'}</h3></div><button type="button" className="icon-btn" onClick={()=>setModal(null)}><X size={18}/></button></div><label>Name<input value={templateForm.name} onChange={e=>setTemplateForm({...templateForm,name:e.target.value})} required/></label><label>Amount<input type="number" min="0.01" step="0.01" value={templateForm.amount} onChange={e=>setTemplateForm({...templateForm,amount:e.target.value})} required/></label><label>Category<select value={templateForm.category} onChange={e=>setTemplateForm({...templateForm,category:e.target.value})}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label>Frequency<select value={templateForm.frequency} onChange={e=>setTemplateForm({...templateForm,frequency:e.target.value})}>{frequencies.map(x=><option key={x}>{x}</option>)}</select></label><label>Description<textarea value={templateForm.description} onChange={e=>setTemplateForm({...templateForm,description:e.target.value})} required/></label><button className="primary full" disabled={loading}>Save recurring cost</button></form></div>}
  {modal==='requisition'&&<div className="modal-backdrop"><form className="modal-card" onSubmit={saveReq}><div className="panel-head"><div><p className="eyebrow">MONTHLY REQUISITION</p><h3>{reqForm.id?'Edit requisition':'New requisition'}</h3></div><button type="button" className="icon-btn" onClick={()=>setModal(null)}><X size={18}/></button></div><label>Amount<input type="number" min="0.01" step="0.01" value={reqForm.amount_requested} onChange={e=>setReqForm({...reqForm,amount_requested:e.target.value})} required/></label><label>Category<select value={reqForm.category} onChange={e=>setReqForm({...reqForm,category:e.target.value})}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label>What is needed?<textarea value={reqForm.description} onChange={e=>setReqForm({...reqForm,description:e.target.value})} required/></label><label>Needed by<input type="date" value={reqForm.needed_date} onChange={e=>setReqForm({...reqForm,needed_date:e.target.value})}/></label><label>Notes<textarea value={reqForm.notes} onChange={e=>setReqForm({...reqForm,notes:e.target.value})}/></label><button className="primary full" disabled={loading}>Submit requisition</button></form></div>}
 </div>
}
