import { useEffect, useMemo, useState } from 'react'
import { CheckCircle2, ChevronRight, Plus, RefreshCw, Search, X } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { supabase } from '../lib/supabase'

const CONFIG = {
  projects: { eyebrow: 'DELIVERY', title: 'Projects', description: 'Create, update and track client delivery work.', columns: ['title','status','start_date','end_date'], fields: [['title','Title','text',true],['description','Description','textarea',false],['owner_id','Client','client',true],['status','Status','projectStatus',true],['start_date','Start date','date',false],['end_date','End date','date',false]] },
  services: { eyebrow: 'OFFERINGS', title: 'Services', description: 'Manage the services presented by the public website.', columns: ['name','slug','is_active','sort_order'], fields: [['name','Name','text',true],['slug','Slug','text',true],['description','Description','textarea',false],['icon','Icon','text',false],['sort_order','Order','number',false],['is_active','Active','boolean',false]] },
  customers: { eyebrow: 'RELATIONSHIPS', title: 'Customers', description: 'Customer records linked to authenticated client accounts.', columns: ['profile.full_name','profile.company','customer_status','notes'], fields: [['profile_id','Account','client',true],['customer_status','Status','customerStatus',true],['notes','Notes','textarea',false]] },
  tickets: { eyebrow: 'SUPPORT', title: 'Tickets', description: 'Own the support queue, assign work and keep clients informed.', columns: ['subject','status','priority','assignee.full_name'], fields: [['subject','Subject','text',true],['client_id','Client','client',true],['assignee_id','Assignee','staff',false],['priority','Priority','priority',true],['status','Status','ticketStatus',true]] },
}
const initial = table => Object.fromEntries((CONFIG[table]?.fields || []).map(([key]) => [key, key==='status' ? (table==='tickets'?'open':'planned') : key==='priority'?'normal' : key==='customer_status'?'active' : key==='is_active'?true : '']))
const labelize = value => String(value||'').replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase())
const formatValue = value => value===null||value===undefined||value===''?'—':typeof value==='boolean'?(value?'Yes':'No'):String(value)

export default function OperationalResourcePage({ table }) {
  const config=CONFIG[table]; const navigate=useNavigate(); const [rows,setRows]=useState([]); const [clients,setClients]=useState([]); const [staff,setStaff]=useState([])
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [search,setSearch]=useState(''); const [selected,setSelected]=useState(null); const [modalOpen,setModalOpen]=useState(false)
  const [form,setForm]=useState(()=>initial(table)); const [message,setMessage]=useState(''); const [error,setError]=useState('')
  const load=async()=>{ setLoading(true); setError(''); let query
    if(table==='customers') query=supabase.from('customers').select('id,profile_id,customer_status,notes,created_at,updated_at,profile:profiles!customers_profile_id_fkey(id,full_name,email,company,phone)').order('updated_at',{ascending:false})
    else if(table==='projects') query=supabase.from('projects').select('id,title,description,status,start_date,end_date,owner_id,created_at,updated_at,owner:profiles!projects_owner_id_fkey(id,full_name,company)').order('updated_at',{ascending:false})
    else if(table==='tickets') query=supabase.from('tickets').select('id,subject,status,priority,client_id,assignee_id,created_at,updated_at,client:profiles!tickets_client_id_fkey(id,full_name),assignee:profiles!tickets_assignee_id_fkey(id,full_name)').order('updated_at',{ascending:false})
    else query=supabase.from(table).select('*').order('updated_at',{ascending:false})
    const [{data,error:loadError},clientResult,staffResult]=await Promise.all([query,supabase.from('profiles').select('id,full_name,role,company').eq('role','client').order('full_name'),supabase.from('profiles').select('id,full_name,role').in('role',['staff','admin']).order('full_name')])
    if(loadError) setError(loadError.message); else setRows(data||[]); setClients(clientResult.data||[]); setStaff(staffResult.data||[]); setLoading(false)
  }
  useEffect(()=>{load()},[table])
  const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return rows.filter(row=>!q||JSON.stringify(row).toLowerCase().includes(q))},[rows,search])
  const openCreate=()=>{setSelected(null);setForm(initial(table));setMessage('');setError('');setModalOpen(true)}
  const openEdit=row=>{setSelected(row);const next=initial(table);for(const [key] of config.fields) next[key]=row[key]??next[key];setForm(next);setMessage('');setError('');setModalOpen(true)}
  const save=async e=>{e.preventDefault();setSaving(true);setError('');setMessage('');const payload={...form};Object.keys(payload).forEach(k=>{if(payload[k]==='')payload[k]=null});if(table==='services'&&!payload.slug)payload.slug=String(payload.name||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');let result=selected?await supabase.from(table).update(payload).eq('id',selected.id).select().single():await supabase.from(table).insert(payload).select().single();if(result.error)setError(result.error.message);else{setMessage(selected?'Record updated successfully.':'Record created successfully.');setModalOpen(false);setForm(initial(table));await load()}setSaving(false)}
  const cell=(row,col)=>{const value=col.includes('.')?col.split('.').reduce((o,k)=>o?.[k],row):row[col];return <span className="table-value">{formatValue(value)}</span>}
  if(!config)return null
  return <div>
    <div className="page-intro"><div><p className="eyebrow">{config.eyebrow}</p><h1>{config.title}</h1><p className="muted">{config.description}</p></div><div className="team-actions"><button className="icon-btn" onClick={load} title="Refresh"><RefreshCw size={16}/></button><button className="primary" onClick={openCreate}><Plus size={16}/> New {table==='customers'?'customer':table.slice(0,-1)}</button></div></div>
    {message&&<div className="alert success"><CheckCircle2 size={15}/> {message}</div>}{error&&<div className="alert danger">{error}</div>}
    <section className="panel"><div className="panel-head"><div><p className="eyebrow">LIVE DATABASE</p><h3>{loading?'Loading…':`${filtered.length} record${filtered.length===1?'':'s'}`}</h3></div><div className="search-box"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search records"/></div></div>{loading?<div className="empty">Loading live records…</div>:filtered.length===0?<div className="empty">No records found. Create the first real record above.</div>:<div className="table-wrap"><table><thead><tr>{config.columns.map(c=><th key={c}>{labelize(c)}</th>)}<th></th></tr></thead><tbody>{filtered.map(row=><tr key={row.id} className="clickable-row" onClick={()=>table==='projects'?navigate(`/projects/${row.id}`):openEdit(row)}>{config.columns.map(c=><td key={c}>{cell(row,c)}</td>)}<td><ChevronRight size={15}/></td></tr>)}</tbody></table></div>}</section>
    {modalOpen&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setModalOpen(false)}><form className="modal-card operational-form" onSubmit={save}><div className="panel-head"><div><p className="eyebrow">{selected?'EDIT RECORD':'NEW RECORD'}</p><h3>{selected?`Edit ${config.title.slice(0,-1)}`:`Create ${table==='customers'?'customer':table.slice(0,-1)}`}</h3></div><button type="button" className="icon-btn" onClick={()=>setModalOpen(false)}><X size={18}/></button></div>
      {config.fields.map(([key,label,type,required])=>{if(type==='projectStatus')return <label key={key}>{label}<select value={form[key]??'planned'} onChange={e=>setForm({...form,[key]:e.target.value})} required={required}><option value="planned">Planned</option><option value="active">Active</option><option value="on_hold">On hold</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></label>;if(type==='ticketStatus')return <label key={key}>{label}<select value={form[key]??'open'} onChange={e=>setForm({...form,[key]:e.target.value})} required={required}><option value="open">Open</option><option value="in_progress">In progress</option><option value="waiting">Waiting</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select></label>;if(type==='priority')return <label key={key}>{label}<select value={form[key]??'normal'} onChange={e=>setForm({...form,[key]:e.target.value})} required={required}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></label>;if(type==='customerStatus')return <label key={key}>{label}<select value={form[key]??'active'} onChange={e=>setForm({...form,[key]:e.target.value})} required={required}><option value="active">Active</option><option value="inactive">Inactive</option><option value="archived">Archived</option></select></label>;if(type==='textarea')return <label key={key}>{label}<textarea value={form[key]??''} onChange={e=>setForm({...form,[key]:e.target.value})} required={required}/></label>;if(type==='boolean')return <label key={key} className="checkbox-field"><input type="checkbox" checked={!!form[key]} onChange={e=>setForm({...form,[key]:e.target.checked})}/>{label}</label>;if(type==='client')return <label key={key}>{label}<select value={form[key]??''} onChange={e=>setForm({...form,[key]:e.target.value})} required={required}><option value="">Select client…</option>{clients.map(x=><option key={x.id} value={x.id}>{x.full_name||'Unnamed'}{x.company?` — ${x.company}`:''}</option>)}</select></label>;if(type==='staff')return <label key={key}>{label}<select value={form[key]??''} onChange={e=>setForm({...form,[key]:e.target.value})}><option value="">Unassigned</option>{staff.map(x=><option key={x.id} value={x.id}>{x.full_name||x.role}</option>)}</select></label>;return <label key={key}>{label}<input type={type} value={form[key]??''} onChange={e=>setForm({...form,[key]:e.target.value})} required={required}/></label>})}
      <button className="primary full" disabled={saving}>{saving?'Saving…':selected?'Save changes':'Create record'}</button></form></div>}
  </div>
}
