import { useEffect, useState } from 'react'
import { NavLink, Navigate, Route, Routes, useLocation, useNavigate } from 'react-router-dom'
import { BarChart3, Bell, BriefcaseBusiness, ChevronRight, CircleUserRound, ClipboardList, FileText, FolderKanban, LayoutDashboard, ListTodo, LogOut, Menu, MessageSquare, Search, Settings, ShieldCheck, Users, Wrench, X } from 'lucide-react'
import { useAuth } from './auth/AuthProvider'
import { isSupabaseConfigured, supabase } from './lib/supabase'
import Dashboard from './components/Dashboard'
import RepairDeskWorkspace from './components/RepairDeskWorkspace'
import FinancePage from './components/FinancePage'
import CustomersPage from './components/CustomersPage'
import TasksPage from './components/TasksPage'
import TeamPage from './components/TeamPage'
import InquiriesPage from './components/InquiriesPage'
import OperationalResourcePage from './components/OperationalResourcePage'
import AdminTicketDetail from './components/AdminTicketDetail'
import AdminProjectDetail from './components/AdminProjectDetail'
import AdminFilesPage from './components/AdminFilesPage'

const navGroups=[
 {label:'OPERATIONS',items:[['/','Overview',LayoutDashboard],['/repairs','Repairs',Wrench],['/customers','Customers',Users],['/projects','Projects',FolderKanban],['/tasks','Tasks',ListTodo]]},
 {label:'CLIENT WORK',items:[['/inquiries','Inquiries',MessageSquare],['/requests','Service Requests',ClipboardList],['/services','Services',Wrench],['/tickets','Tickets',BriefcaseBusiness]]},
 {label:'FINANCE',items:[['/finance','Finance',BarChart3],['/reports','Reports',BarChart3]]},
 {label:'ADMINISTRATION',items:[['/team','Team',CircleUserRound],['/files','Files',FileText],['/notifications','Notifications',Bell],['/settings','Settings',Settings]]},
]
const nav=navGroups.flatMap(group=>group.items)
const titleFor=path=>{const exact=nav.find(x=>x[0]===path);if(exact)return exact[1];const match=nav.find(x=>x[0]!=='/'&&path.startsWith(`${x[0]}/`));return match?.[1]||'Overview'}
function Login(){const{signIn}=useAuth();const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const navigate=useNavigate();async function submit(e){e.preventDefault();setBusy(true);setError('');try{await signIn(email.trim(),password);navigate('/')}catch(err){setError(err.message||'Unable to sign in.')}finally{setBusy(false)}}return <div className="auth-shell"><div className="auth-grid"/><form className="login-card" onSubmit={submit}><div className="brand-mark"><span>⚡</span> CYPHER TECHNOLOGIES</div><p className="eyebrow">INTERNAL OPERATIONS</p><h1>Secure staff access</h1><p className="muted">Sign in with an authorized staff or administrator account.</p>{!isSupabaseConfigured&&<div className="alert warning">Authentication is not configured.</div>}{error&&<div className="alert danger">{error}</div>}<label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" autoComplete="username" required/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" autoComplete="current-password" required/></label><NavLink to="/forgot-password" className="text-link">Forgot password?</NavLink><button className="primary full" disabled={busy||!isSupabaseConfigured}>{busy?'Signing in…':'Sign in'} <ChevronRight size={17}/></button><div className="security-note"><ShieldCheck size={16}/> Supabase Auth, role controls and database RLS protect this workspace.</div></form></div>}
function ForgotPassword(){const{requestPasswordReset}=useAuth();const[email,setEmail]=useState('');const[sent,setSent]=useState(false);const[error,setError]=useState('');async function submit(e){e.preventDefault();setError('');try{await requestPasswordReset(email);setSent(true)}catch(err){setError(err.message)}}return <div className="auth-shell"><div className="login-card"><div className="brand-mark"><span>⚡</span> CYPHER TECHNOLOGIES</div><p className="eyebrow">ACCOUNT RECOVERY</p><h1>Reset your password</h1>{error&&<div className="alert danger">{error}</div>}{sent&&<div className="alert success">Check your email for the secure reset link.</div>}<form onSubmit={submit}><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required/></label><button className="primary full">Send reset link</button></form><NavLink to="/login" className="text-link">← Back to sign in</NavLink></div></div>}
function Shell({children}){const{profile,signOut}=useAuth();const[mobile,setMobile]=useState(false);const location=useLocation();const initials=(profile?.full_name||'Cypher').split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase();return <div className="app-shell"><aside className={`sidebar ${mobile?'open':''}`}><div className="sidebar-head"><div className="brand-mark"><span>⚡</span> CYPHER</div><button className="icon-btn mobile-only" onClick={()=>setMobile(false)}><X size={19}/></button></div><div className="portal-label">ADMIN CONSOLE <span>v1</span></div>{navGroups.map(group=><div key={group.label}><div className="portal-label">{group.label}</div><nav>{group.items.map(([path,label,Icon])=><NavLink key={path} to={path} end={path==='/' } onClick={()=>setMobile(false)} className={({isActive})=>isActive?'active':''}><Icon size={18}/><span>{label}</span></NavLink>)}</nav></div>)}<div className="sidebar-foot"><div className="profile-mini"><div className="avatar">{initials}</div><div><strong>{profile?.full_name||'Staff member'}</strong><small>{profile?.role||'staff'}</small></div></div><button className="logout" onClick={signOut}><LogOut size={17}/> Sign out</button></div></aside>{mobile&&<button className="scrim" onClick={()=>setMobile(false)} aria-label="Close navigation"/>}<main className="main"><header className="topbar"><button className="icon-btn mobile-only" onClick={()=>setMobile(true)}><Menu size={21}/></button><div><span className="crumb">CYPHER / INTERNAL</span><h2>{titleFor(location.pathname)}</h2></div><div className="top-actions"><button className="icon-btn" title="Search"><Search size={18}/></button><NavLink className="icon-btn" to="/notifications"><Bell size={18}/></NavLink><div className="status"><i/> Systems online</div></div></header><section className="content">{children}</section></main></div>}
function NotificationsPage(){const[items,setItems]=useState([]);const[error,setError]=useState('');const load=async()=>{const{data,error:e}=await supabase.from('notifications').select('id,type,payload,read_at,created_at').order('created_at',{ascending:false}).limit(100);if(e)setError(e.message);else setItems(data||[])};useEffect(()=>{load()},[]);const mark=async id=>{const{error:e}=await supabase.from('notifications').update({read_at:new Date().toISOString()}).eq('id',id);if(!e)setItems(xs=>xs.map(x=>x.id===id?{...x,read_at:new Date().toISOString()}:x))};return <div><div className="page-intro"><div><p className="eyebrow">SYSTEM ACTIVITY</p><h1>Notifications</h1><p className="muted">Events generated by the shared business workflow.</p></div></div>{error&&<div className="alert danger">{error}</div>}<section className="panel"><div className="table-wrap"><table><thead><tr><th>Type</th><th>Event</th><th>Created</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><span className="chip">{x.type}</span></td><td>{JSON.stringify(x.payload)}</td><td>{new Date(x.created_at).toLocaleString()}</td><td>{!x.read_at&&<button className="text-link" onClick={()=>mark(x.id)}>Mark read</button>}</td></tr>)}</tbody></table></div>{!items.length&&<div className="empty">No notifications yet.</div>}</section></div>}
function ReportsPage(){const[state,setState]=useState({overview:{},months:[],loading:true,error:''});useEffect(()=>{Promise.all([supabase.from('dashboard_overview').select('*').single(),supabase.from('finance_monthly_summary').select('*').order('month_start',{ascending:false}).limit(6)]).then(([a,b])=>setState({overview:a.data||{},months:b.data||[],loading:false,error:a.error?.message||b.error?.message||''})).catch(err=>setState(x=>({...x,loading:false,error:err.message||'Unable to load reports.'})))},[]);return <div><div className="page-intro"><div><p className="eyebrow">BUSINESS INTELLIGENCE</p><h1>Reports</h1><p className="muted">Live financial and operational reporting.</p></div></div>{state.error&&<div className="alert danger">{state.error}</div>}<div className="metric-grid">{[['Active repairs',state.overview.active_repairs],['Repairs with balance',state.overview.repairs_with_balance],['Active projects',state.overview.active_projects],['Open project tasks',state.overview.open_project_tasks]].map(([x,y])=><div className="metric" key={x}><span>{x}</span><strong>{y??'—'}</strong><small>Current database count</small></div>)}</div><section className="panel"><div className="panel-head"><div><p className="eyebrow">MONTHLY FINANCE</p><h3>Income, expenses, deductions and net position</h3></div></div><div className="table-wrap"><table><thead><tr><th>Month</th><th>Income</th><th>Expenses</th><th>Deductions</th><th>Net</th></tr></thead><tbody>{(state.months||[]).map(x=><tr key={x.month_start}><td>{new Date(`${x.month_start}T00:00:00`).toLocaleDateString([], {year:'numeric',month:'long'})}</td><td>{Number(x.income||0).toFixed(2)}</td><td>{Number(x.expenses||0).toFixed(2)}</td><td>{Number(x.deductions||0).toFixed(2)}</td><td><strong>{Number(x.net_position||0).toFixed(2)}</strong></td></tr>)}</tbody></table></div></section></div>}
function SettingsPage(){const{profile,updateProfile}=useAuth();const[form,setForm]=useState({full_name:profile?.full_name||'',phone:profile?.phone||'',company:profile?.company||''});const[saved,setSaved]=useState(false);const[error,setError]=useState('');async function save(e){e.preventDefault();setError('');try{await updateProfile(form);setSaved(true)}catch(err){setError(err.message)}}return <div><div className="page-intro"><div><p className="eyebrow">ACCOUNT</p><h1>Settings</h1><p className="muted">Keep your internal staff profile current.</p></div></div><section className="panel"><form className="modal-card" onSubmit={save}><label>Full name<input value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})} required/></label><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Company<input value={form.company} onChange={e=>setForm({...form,company:e.target.value})}/></label>{error&&<div className="alert danger">{error}</div>}{saved&&<div className="alert success">Profile saved.</div>}<button className="primary">Save profile</button></form></section></div>}
function ResetPassword(){const{session,updatePassword}=useAuth();const[p,setP]=useState('');const[c,setC]=useState('');const[e,setE]=useState('');const nav=useNavigate();async function save(x){x.preventDefault();if(p.length<8)return setE('Password must be at least 8 characters.');if(p!==c)return setE('Passwords do not match.');try{await updatePassword(p);nav('/')}catch(err){setE(err.message)}}if(!session)return <Navigate to="/login" replace/>;return <div className="auth-shell"><form className="login-card" onSubmit={save}><div className="brand-mark"><span>⚡</span> CYPHER TECHNOLOGIES</div><h1>Set a new password</h1>{e&&<div className="alert danger">{e}</div>}<label>New password<input type="password" value={p} onChange={x=>setP(x.target.value)} minLength={8} required/></label><label>Confirm password<input type="password" value={c} onChange={x=>setC(x.target.value)} minLength={8} required/></label><button className="primary full">Update password</button></form></div>}
function Protected(){const{session,loading,profile}=useAuth();if(loading)return <div className="loading">Loading secure workspace…</div>;if(!session)return <Navigate to="/login" replace/>;if(!['admin','staff'].includes(profile?.role))return <Login/>;return <Shell><Routes><Route path="/" element={<Dashboard/>}/><Route path="/inquiries" element={<InquiriesPage/>}/><Route path="/requests" element={<InquiriesPage/>}/><Route path="/repairs" element={<RepairDeskWorkspace/>}/><Route path="/customers" element={<CustomersPage/>}/><Route path="/finance" element={<FinancePage/>}/><Route path="/projects" element={<OperationalResourcePage table="projects"/>}/><Route path="/projects/:projectId" element={<AdminProjectDetail/>}/><Route path="/tasks" element={<TasksPage/>}/><Route path="/services" element={<OperationalResourcePage table="services"/>}/><Route path="/tickets" element={<OperationalResourcePage table="tickets"/>}/><Route path="/tickets/:ticketId" element={<AdminTicketDetail/>}/><Route path="/team" element={<TeamPage/>}/><Route path="/files" element={<AdminFilesPage/>}/><Route path="/notifications" element={<NotificationsPage/>}/><Route path="/reports" element={<ReportsPage/>}/><Route path="/settings" element={<SettingsPage/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes></Shell>}
export default function OperationalApp(){return <Routes><Route path="/login" element={<Login/>}/><Route path="/forgot-password" element={<ForgotPassword/>}/><Route path="/reset-password" element={<ResetPassword/>}/><Route path="/*" element={<Protected/>}/></Routes>}
